#!/usr/bin/env bun
/**
 * Runs Terraform against LocalStack.
 *
 * The production stack keeps its state in S3, declared as a partial backend
 * in infra/versions.tf. A LocalStack run must not touch that bucket, so this
 * writes a Terraform override file selecting the local backend, then runs the
 * requested command. Override files are gitignored, so it cannot leak into a
 * commit and change where production state lives.
 *
 * Only the state location differs. The infrastructure itself is the same
 * configuration in both cases (ADR-0005, ADR-0007).
 */
import { $ } from "bun";

const ENDPOINT = "http://localhost:4566";
const ENVIRONMENT = "local";
const OVERRIDE = "infra/backend_override.tf";

const ALLOWED = new Set(["plan", "apply", "destroy", "output", "show"]);

const [command = "plan", ...rest] = Bun.argv.slice(2);

if (!ALLOWED.has(command)) {
  console.error(
    `Unsupported command "${command}". Expected one of: ${[...ALLOWED].join(", ")}`,
  );
  process.exit(2);
}

await Bun.write(
  OVERRIDE,
  `# Generated by scripts/tf-local.ts. Not committed: see .gitignore.
# Overrides the S3 backend in versions.tf so LocalStack runs keep state here.
terraform {
  backend "local" {}
}
`,
);

await $`terraform -chdir=infra init -reconfigure -input=false`.quiet();

const autoApprove = command === "apply" || command === "destroy";

await $`terraform -chdir=infra ${command} -input=false ${
  autoApprove ? ["-auto-approve"] : []
} ${
  command === "output" || command === "show"
    ? []
    : [
        "-var",
        `localstack_endpoint=${ENDPOINT}`,
        "-var",
        `environment=${ENVIRONMENT}`,
      ]
} ${rest}`;
